clouds:

  my_ec2:
    name: 'my_ec2'
    type: 'aws'
    key_name: ''
    key_path: ''
    aws_access_key_id: ''
    aws_secret_access_key: ''
    ec2_region_name: ''
    use_external_resource: false
    resource_id: ''
    parameters: {}

  my_openstack:
    name: 'my_openstack'
    type: 'openstack'
    key_name: ''
    key_path: ''
    username: ''
    password: ''
    tenant_name: ''
    auth_url: ''
    region: ''
    nova_url: ''
    neutron_url: ''

