clouds:
  
  hp_cloud:
    name: 'hp_cloud_giga'
    type: 'openstack'
    parameters:
      username: ''
      password: ''
      tenant_name: ''
      auth_url: ''
      region: ''
      nova_url: ''
      neutron_url: ''

  aws_ec2:
    name: 'ec2_giga'
    type: 'aws'
    parameters:
      aws_config:
        aws_access_key_id: ''
        aws_secret_access_key: ''
        ec2_region_name: ''
      use_external_resource: false
      resource_id: ''
      parameters: {}